app_hello:
    path: /
    controller: App\Controller\AccueilController::index


app_contact:
    path: /contact
    controller: App\Controller\ContactController::index


app_service:
    path: /service
    controller: App\Controller\ServiceController::index

