app_hello:
    path: /
    controller: App\Controller\AccueilController::index


app_contact:
    path: /contact
    controller: App\Controller\ContactController::contact


app_service:
    path: /service
    controller: App\Controller\ServiceController::service

app_habitat:
    path: /habitat
    controller: App\Controller\HabitatController::habitat



app_connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::connexion


